name: Build, Test, and Upload Python Package

on:
  push:
    tags:
      - "v*.*.*"
      
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # test:
  #      uses: ./.github/workflows/ubuntu-python-package.yml  # use the callable tests job to run tests

  deploy:
    runs-on: docker
    container:
      image: node:22-bookworm

  #  needs: [test]

    steps:
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y curl python3 python3-venv python3-pip
        curl -sL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs
        node --version
        npm --version
        
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip

    - name: Publish to PyPI
      run: |
        python -m venv venv
        . ./venv/bin/activate
        pip install -U twine build
        python -m build .
        python -m twine upload --repository pypi --username __token__ --password ${{ secrets.PYPI }} dist/* 
      env:
        PYPI: ${{ secrets.PYPI }}
