import logging
from PyQt6.QtWidgets import QWidget, QLabel, QLineEdit, QHBoxLayout, QSizePolicy, QSpacerItem, QVBoxLayout
from PyQt6.QtCore import Qt
from nqrduck.module.module_view import ModuleView

logger = logging.getLogger(__name__)


class BaseSpectrometerView(ModuleView):
    
    def __init__(self, module):
        super().__init__(module)

    def load_settings_ui(self):
        """This method automaticall generates a view for the settings of the module.
        If there is a widget file that has been generated by Qt Designer, it will be used. Otherwise, a default view will be generated."""
        
        from .base_spectrometer_widget import Ui_Form
        widget = QWidget()
        widget.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        self._ui_form = Ui_Form()
        self.widget = widget
        self._ui_form.setupUi(self)

        grid = self._ui_form.gridLayout
        self._ui_form.verticalLayout.removeItem(self._ui_form.gridLayout)
        # Add name of the spectrometer to the view
        label = QLabel("%s Settings:" % self.module.model.toolbar_name)
        label.setStyleSheet("font-weight: bold;")
        self._ui_form.verticalLayout.setSpacing(5)
        self._ui_form.verticalLayout.addWidget(label)
        self._ui_form.verticalLayout.addLayout(grid)

        for category_count, category in enumerate(self.module.model.settings.keys()):
            logger.debug("Adding settings for category: %s", category)
            category_layout = QVBoxLayout()
            category_label = QLabel("%s:" % category)
            category_label.setStyleSheet("font-weight: bold;")
            row = category_count // 2
            column = category_count % 2

            category_layout.addWidget(category_label)
            for setting in self.module.model.settings[category]:
                logger.debug("Adding setting to settings view: %s", setting.name)
                
                spacer = QSpacerItem(20, 20)
                # Create a label for the setting
                setting_label = QLabel(setting.name)
                setting_label.setMinimumWidth(200)
                # Add an QLineEdit for the setting
                line_edit = QLineEdit(str(setting.value))
                line_edit.setMinimumWidth(100)
                # Add a horizontal layout for the setting
                layout = QHBoxLayout()
                # Connect the editingFinished signal to the on_value_changed slot of the setting
                line_edit.editingFinished.connect(lambda x=line_edit: setting.on_value_changed(x.text()))
                # Add the label and the line edit to the layout
                layout.addItem(spacer)
                layout.addWidget(setting_label)
                layout.addWidget(line_edit)
                layout.addStretch(1)
                # Add the layout to the vertical layout of the widget
                category_layout.addLayout(layout)
            
            category_layout.addStretch(1)
            self._ui_form.gridLayout.addLayout(category_layout, row, column)
            
        
        # Push all the settings to the top of the widget
        self._ui_form.verticalLayout.addStretch(1)
        