from PyQt5.QtCore import pyqtSignal, QObject
from nqrduck.module.module import Module
from nqrduck_spectrometer.spectrometer_model import SpectrometerModel
from nqrduck_spectrometer.spectrometer_view import SpectrometerView
from nqrduck_spectrometer.spectrometer_controller import SpectrometerController
from nqrduck_spectrometer.spectrometer_widget import Ui_Form

Spectrometer = Module(SpectrometerModel, SpectrometerController, SpectrometerView)